<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesKeysSeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['name' => 'Saudi Arabia', 'key' => '+966', 'icon' => 'https://flagcdn.com/w80/sa.png'],
            ['name' => 'Afghanistan', 'key' => '+93', 'icon' => 'https://flagcdn.com/w80/af.png'],
            ['name' => 'Albania', 'key' => '+355', 'icon' => 'https://flagcdn.com/w80/al.png'],
            ['name' => 'Algeria', 'key' => '+213', 'icon' => 'https://flagcdn.com/w80/dz.png'],
            ['name' => 'Andorra', 'key' => '+376', 'icon' => 'https://flagcdn.com/w80/ad.png'],
            ['name' => 'Angola', 'key' => '+244', 'icon' => 'https://flagcdn.com/w80/ao.png'],
            ['name' => 'Antigua and Barbuda', 'key' => '+1-268', 'icon' => 'https://flagcdn.com/w80/ag.png'],
            ['name' => 'Argentina', 'key' => '+54', 'icon' => 'https://flagcdn.com/w80/ar.png'],
            ['name' => 'Armenia', 'key' => '+374', 'icon' => 'https://flagcdn.com/w80/am.png'],
            ['name' => 'Australia', 'key' => '+61', 'icon' => 'https://flagcdn.com/w80/au.png'],
            ['name' => 'Austria', 'key' => '+43', 'icon' => 'https://flagcdn.com/w80/at.png'],
            ['name' => 'Azerbaijan', 'key' => '+994', 'icon' => 'https://flagcdn.com/w80/az.png'],
            ['name' => 'Bahamas', 'key' => '+1-242', 'icon' => 'https://flagcdn.com/w80/bs.png'],
            ['name' => 'Bahrain', 'key' => '+973', 'icon' => 'https://flagcdn.com/w80/bh.png'],
            ['name' => 'Bangladesh', 'key' => '+880', 'icon' => 'https://flagcdn.com/w80/bd.png'],
            ['name' => 'Barbados', 'key' => '+1-246', 'icon' => 'https://flagcdn.com/w80/bb.png'],
            ['name' => 'Belarus', 'key' => '+375', 'icon' => 'https://flagcdn.com/w80/by.png'],
            ['name' => 'Belgium', 'key' => '+32', 'icon' => 'https://flagcdn.com/w80/be.png'],
            ['name' => 'Belize', 'key' => '+501', 'icon' => 'https://flagcdn.com/w80/bz.png'],
            ['name' => 'Benin', 'key' => '+229', 'icon' => 'https://flagcdn.com/w80/bj.png'],
            ['name' => 'Bhutan', 'key' => '+975', 'icon' => 'https://flagcdn.com/w80/bt.png'],
            ['name' => 'Bolivia', 'key' => '+591', 'icon' => 'https://flagcdn.com/w80/bo.png'],
            ['name' => 'Bosnia and Herzegovina', 'key' => '+387', 'icon' => 'https://flagcdn.com/w80/ba.png'],
            ['name' => 'Botswana', 'key' => '+267', 'icon' => 'https://flagcdn.com/w80/bw.png'],
            ['name' => 'Brazil', 'key' => '+55', 'icon' => 'https://flagcdn.com/w80/br.png'],
            ['name' => 'Brunei', 'key' => '+673', 'icon' => 'https://flagcdn.com/w80/bn.png'],
            ['name' => 'Bulgaria', 'key' => '+359', 'icon' => 'https://flagcdn.com/w80/bg.png'],
            ['name' => 'Burkina Faso', 'key' => '+226', 'icon' => 'https://flagcdn.com/w80/bf.png'],
            ['name' => 'Burundi', 'key' => '+257', 'icon' => 'https://flagcdn.com/w80/bi.png'],
            ['name' => 'Cabo Verde', 'key' => '+238', 'icon' => 'https://flagcdn.com/w80/cv.png'],
            ['name' => 'Cambodia', 'key' => '+855', 'icon' => 'https://flagcdn.com/w80/kh.png'],
            ['name' => 'Cameroon', 'key' => '+237', 'icon' => 'https://flagcdn.com/w80/cm.png'],
            ['name' => 'Canada', 'key' => '+1', 'icon' => 'https://flagcdn.com/w80/ca.png'],
            ['name' => 'Central African Republic', 'key' => '+236', 'icon' => 'https://flagcdn.com/w80/cf.png'],
            ['name' => 'Chad', 'key' => '+235', 'icon' => 'https://flagcdn.com/w80/td.png'],
            ['name' => 'Chile', 'key' => '+56', 'icon' => 'https://flagcdn.com/w80/cl.png'],
            ['name' => 'China', 'key' => '+86', 'icon' => 'https://flagcdn.com/w80/cn.png'],
            ['name' => 'Colombia', 'key' => '+57', 'icon' => 'https://flagcdn.com/w80/co.png'],
            ['name' => 'Comoros', 'key' => '+269', 'icon' => 'https://flagcdn.com/w80/km.png'],
            ['name' => 'Congo (Congo-Brazzaville)', 'key' => '+242', 'icon' => 'https://flagcdn.com/w80/cg.png'],
            ['name' => 'Congo (DRC)', 'key' => '+243', 'icon' => 'https://flagcdn.com/w80/cd.png'],
            ['name' => 'Costa Rica', 'key' => '+506', 'icon' => 'https://flagcdn.com/w80/cr.png'],
            ['name' => 'Croatia', 'key' => '+385', 'icon' => 'https://flagcdn.com/w80/hr.png'],
            ['name' => 'Cuba', 'key' => '+53', 'icon' => 'https://flagcdn.com/w80/cu.png'],
            ['name' => 'Cyprus', 'key' => '+357', 'icon' => 'https://flagcdn.com/w80/cy.png'],
            ['name' => 'Czech Republic', 'key' => '+420', 'icon' => 'https://flagcdn.com/w80/cz.png'],
            ['name' => 'Denmark', 'key' => '+45', 'icon' => 'https://flagcdn.com/w80/dk.png'],
            ['name' => 'Djibouti', 'key' => '+253', 'icon' => 'https://flagcdn.com/w80/dj.png'],
            ['name' => 'Dominica', 'key' => '+1-767', 'icon' => 'https://flagcdn.com/w80/dm.png'],
            ['name' => 'Dominican Republic', 'key' => '+1-809', 'icon' => 'https://flagcdn.com/w80/do.png'],
            ['name' => 'Ecuador', 'key' => '+593', 'icon' => 'https://flagcdn.com/w80/ec.png'],
            ['name' => 'Egypt', 'key' => '+20', 'icon' => 'https://flagcdn.com/w80/eg.png'],
            ['name' => 'El Salvador', 'key' => '+503', 'icon' => 'https://flagcdn.com/w80/sv.png'],
            ['name' => 'Equatorial Guinea', 'key' => '+240', 'icon' => 'https://flagcdn.com/w80/gq.png'],
            ['name' => 'Eritrea', 'key' => '+291', 'icon' => 'https://flagcdn.com/w80/er.png'],
            ['name' => 'Estonia', 'key' => '+372', 'icon' => 'https://flagcdn.com/w80/ee.png'],
            ['name' => 'Eswatini', 'key' => '+268', 'icon' => 'https://flagcdn.com/w80/sz.png'],
            ['name' => 'Ethiopia', 'key' => '+251', 'icon' => 'https://flagcdn.com/w80/et.png'],
            ['name' => 'Fiji', 'key' => '+679', 'icon' => 'https://flagcdn.com/w80/fj.png'],
            ['name' => 'Finland', 'key' => '+358', 'icon' => 'https://flagcdn.com/w80/fi.png'],
            ['name' => 'France', 'key' => '+33', 'icon' => 'https://flagcdn.com/w80/fr.png'],
            ['name' => 'Gabon', 'key' => '+241', 'icon' => 'https://flagcdn.com/w80/ga.png'],
            ['name' => 'Gambia', 'key' => '+220', 'icon' => 'https://flagcdn.com/w80/gm.png'],
            ['name' => 'Georgia', 'key' => '+995', 'icon' => 'https://flagcdn.com/w80/ge.png'],
            ['name' => 'Germany', 'key' => '+49', 'icon' => 'https://flagcdn.com/w80/de.png'],
            ['name' => 'Ghana', 'key' => '+233', 'icon' => 'https://flagcdn.com/w80/gh.png'],
            ['name' => 'Greece', 'key' => '+30', 'icon' => 'https://flagcdn.com/w80/gr.png'],
            ['name' => 'Grenada', 'key' => '+1-473', 'icon' => 'https://flagcdn.com/w80/gd.png'],
            ['name' => 'Guatemala', 'key' => '+502', 'icon' => 'https://flagcdn.com/w80/gt.png'],
            ['name' => 'Guinea', 'key' => '+224', 'icon' => 'https://flagcdn.com/w80/gn.png'],
            ['name' => 'Guinea-Bissau', 'key' => '+245', 'icon' => 'https://flagcdn.com/w80/gw.png'],
            ['name' => 'Guyana', 'key' => '+592', 'icon' => 'https://flagcdn.com/w80/gy.png'],
            ['name' => 'Haiti', 'key' => '+509', 'icon' => 'https://flagcdn.com/w80/ht.png'],
            ['name' => 'Honduras', 'key' => '+504', 'icon' => 'https://flagcdn.com/w80/hn.png'],
            ['name' => 'Hungary', 'key' => '+36', 'icon' => 'https://flagcdn.com/w80/hu.png'],
            ['name' => 'Iceland', 'key' => '+354', 'icon' => 'https://flagcdn.com/w80/is.png'],
            ['name' => 'India', 'key' => '+91', 'icon' => 'https://flagcdn.com/w80/in.png'],
            ['name' => 'Indonesia', 'key' => '+62', 'icon' => 'https://flagcdn.com/w80/id.png'],
            ['name' => 'Iran', 'key' => '+98', 'icon' => 'https://flagcdn.com/w80/ir.png'],
            ['name' => 'Iraq', 'key' => '+964', 'icon' => 'https://flagcdn.com/w80/iq.png'],
            ['name' => 'Ireland', 'key' => '+353', 'icon' => 'https://flagcdn.com/w80/ie.png'],
            ['name' => 'Israel', 'key' => '+972', 'icon' => 'https://flagcdn.com/w80/il.png'],
            ['name' => 'Italy', 'key' => '+39', 'icon' => 'https://flagcdn.com/w80/it.png'],
            ['name' => 'Jamaica', 'key' => '+1-876', 'icon' => 'https://flagcdn.com/w80/jm.png'],
            ['name' => 'Japan', 'key' => '+81', 'icon' => 'https://flagcdn.com/w80/jp.png'],
            ['name' => 'Jordan', 'key' => '+962', 'icon' => 'https://flagcdn.com/w80/jo.png'],
            ['name' => 'Kazakhstan', 'key' => '+7', 'icon' => 'https://flagcdn.com/w80/kz.png'],
            ['name' => 'Kenya', 'key' => '+254', 'icon' => 'https://flagcdn.com/w80/ke.png'],
            ['name' => 'Kiribati', 'key' => '+686', 'icon' => 'https://flagcdn.com/w80/ki.png'],
            ['name' => 'Kuwait', 'key' => '+965', 'icon' => 'https://flagcdn.com/w80/kw.png'],
            ['name' => 'Kyrgyzstan', 'key' => '+996', 'icon' => 'https://flagcdn.com/w80/kg.png'],
            ['name' => 'Laos', 'key' => '+856', 'icon' => 'https://flagcdn.com/w80/la.png'],
            ['name' => 'Latvia', 'key' => '+371', 'icon' => 'https://flagcdn.com/w80/lv.png'],
            ['name' => 'Lebanon', 'key' => '+961', 'icon' => 'https://flagcdn.com/w80/lb.png'],
            ['name' => 'Lesotho', 'key' => '+266', 'icon' => 'https://flagcdn.com/w80/ls.png'],
            ['name' => 'Liberia', 'key' => '+231', 'icon' => 'https://flagcdn.com/w80/lr.png'],
            ['name' => 'Libya', 'key' => '+218', 'icon' => 'https://flagcdn.com/w80/ly.png'],
            ['name' => 'Liechtenstein', 'key' => '+423', 'icon' => 'https://flagcdn.com/w80/li.png'],
            ['name' => 'Lithuania', 'key' => '+370', 'icon' => 'https://flagcdn.com/w80/lt.png'],
            ['name' => 'Luxembourg', 'key' => '+352', 'icon' => 'https://flagcdn.com/w80/lu.png'],
            ['name' => 'Madagascar', 'key' => '+261', 'icon' => 'https://flagcdn.com/w80/mg.png'],
            ['name' => 'Malawi', 'key' => '+265', 'icon' => 'https://flagcdn.com/w80/mw.png'],
            ['name' => 'Malaysia', 'key' => '+60', 'icon' => 'https://flagcdn.com/w80/my.png'],
            ['name' => 'Maldives', 'key' => '+960', 'icon' => 'https://flagcdn.com/w80/mv.png'],
            ['name' => 'Mali', 'key' => '+223', 'icon' => 'https://flagcdn.com/w80/ml.png'],
            ['name' => 'Malta', 'key' => '+356', 'icon' => 'https://flagcdn.com/w80/mt.png'],
            ['name' => 'Marshall Islands', 'key' => '+692', 'icon' => 'https://flagcdn.com/w80/mh.png'],
            ['name' => 'Mauritania', 'key' => '+222', 'icon' => 'https://flagcdn.com/w80/mr.png'],
            ['name' => 'Mauritius', 'key' => '+230', 'icon' => 'https://flagcdn.com/w80/mu.png'],
            ['name' => 'Mexico', 'key' => '+52', 'icon' => 'https://flagcdn.com/w80/mx.png'],
            ['name' => 'Micronesia', 'key' => '+691', 'icon' => 'https://flagcdn.com/w80/fm.png'],
            ['name' => 'Moldova', 'key' => '+373', 'icon' => 'https://flagcdn.com/w80/md.png'],
            ['name' => 'Monaco', 'key' => '+377', 'icon' => 'https://flagcdn.com/w80/mc.png'],
            ['name' => 'Mongolia', 'key' => '+976', 'icon' => 'https://flagcdn.com/w80/mn.png'],
            ['name' => 'Montenegro', 'key' => '+382', 'icon' => 'https://flagcdn.com/w80/me.png'],
            ['name' => 'Morocco', 'key' => '+212', 'icon' => 'https://flagcdn.com/w80/ma.png'],
            ['name' => 'Mozambique', 'key' => '+258', 'icon' => 'https://flagcdn.com/w80/mz.png'],
            ['name' => 'Myanmar (Burma)', 'key' => '+95', 'icon' => 'https://flagcdn.com/w80/mm.png'],
            ['name' => 'Namibia', 'key' => '+264', 'icon' => 'https://flagcdn.com/w80/na.png'],
            ['name' => 'Nauru', 'key' => '+674', 'icon' => 'https://flagcdn.com/w80/nr.png'],
            ['name' => 'Nepal', 'key' => '+977', 'icon' => 'https://flagcdn.com/w80/np.png'],
            ['name' => 'Netherlands', 'key' => '+31', 'icon' => 'https://flagcdn.com/w80/nl.png'],
            ['name' => 'New Zealand', 'key' => '+64', 'icon' => 'https://flagcdn.com/w80/nz.png'],
            ['name' => 'Nicaragua', 'key' => '+505', 'icon' => 'https://flagcdn.com/w80/ni.png'],
            ['name' => 'Niger', 'key' => '+227', 'icon' => 'https://flagcdn.com/w80/ne.png'],
            ['name' => 'Nigeria', 'key' => '+234', 'icon' => 'https://flagcdn.com/w80/ng.png'],
            ['name' => 'North Korea', 'key' => '+850', 'icon' => 'https://flagcdn.com/w80/kp.png'],
            ['name' => 'North Macedonia', 'key' => '+389', 'icon' => 'https://flagcdn.com/w80/mk.png'],
            ['name' => 'Norway', 'key' => '+47', 'icon' => 'https://flagcdn.com/w80/no.png'],
            ['name' => 'Oman', 'key' => '+968', 'icon' => 'https://flagcdn.com/w80/om.png'],
            ['name' => 'Pakistan', 'key' => '+92', 'icon' => 'https://flagcdn.com/w80/pk.png'],
            ['name' => 'Palau', 'key' => '+680', 'icon' => 'https://flagcdn.com/w80/pw.png'],
            ['name' => 'Palestine', 'key' => '+970', 'icon' => 'https://flagcdn.com/w80/ps.png'],
            ['name' => 'Panama', 'key' => '+507', 'icon' => 'https://flagcdn.com/w80/pa.png'],
            ['name' => 'Papua New Guinea', 'key' => '+675', 'icon' => 'https://flagcdn.com/w80/pg.png'],
            ['name' => 'Paraguay', 'key' => '+595', 'icon' => 'https://flagcdn.com/w80/py.png'],
            ['name' => 'Peru', 'key' => '+51', 'icon' => 'https://flagcdn.com/w80/pe.png'],
            ['name' => 'Philippines', 'key' => '+63', 'icon' => 'https://flagcdn.com/w80/ph.png'],
            ['name' => 'Poland', 'key' => '+48', 'icon' => 'https://flagcdn.com/w80/pl.png'],
            ['name' => 'Portugal', 'key' => '+351', 'icon' => 'https://flagcdn.com/w80/pt.png'],
            ['name' => 'Qatar', 'key' => '+974', 'icon' => 'https://flagcdn.com/w80/qa.png'],
            ['name' => 'Romania', 'key' => '+40', 'icon' => 'https://flagcdn.com/w80/ro.png'],
            ['name' => 'Russia', 'key' => '+7', 'icon' => 'https://flagcdn.com/w80/ru.png'],
            ['name' => 'Rwanda', 'key' => '+250', 'icon' => 'https://flagcdn.com/w80/rw.png'],
            ['name' => 'Saint Kitts and Nevis', 'key' => '+1-869', 'icon' => 'https://flagcdn.com/w80/kn.png'],
            ['name' => 'Saint Lucia', 'key' => '+1-758', 'icon' => 'https://flagcdn.com/w80/lc.png'],
            ['name' => 'Saint Vincent and the Grenadines', 'key' => '+1-784', 'icon' => 'https://flagcdn.com/w80/vc.png'],
            ['name' => 'Samoa', 'key' => '+685', 'icon' => 'https://flagcdn.com/w80/ws.png'],
            ['name' => 'San Marino', 'key' => '+378', 'icon' => 'https://flagcdn.com/w80/sm.png'],
            ['name' => 'Sao Tome and Principe', 'key' => '+239', 'icon' => 'https://flagcdn.com/w80/st.png'],
            ['name' => 'Senegal', 'key' => '+221', 'icon' => 'https://flagcdn.com/w80/sn.png'],
            ['name' => 'Serbia', 'key' => '+381', 'icon' => 'https://flagcdn.com/w80/rs.png'],
            ['name' => 'Seychelles', 'key' => '+248', 'icon' => 'https://flagcdn.com/w80/sc.png'],
            ['name' => 'Sierra Leone', 'key' => '+232', 'icon' => 'https://flagcdn.com/w80/sl.png'],
            ['name' => 'Singapore', 'key' => '+65', 'icon' => 'https://flagcdn.com/w80/sg.png'],
            ['name' => 'Slovakia', 'key' => '+421', 'icon' => 'https://flagcdn.com/w80/sk.png'],
            ['name' => 'Slovenia', 'key' => '+386', 'icon' => 'https://flagcdn.com/w80/si.png'],
            ['name' => 'Solomon Islands', 'key' => '+677', 'icon' => 'https://flagcdn.com/w80/sb.png'],
            ['name' => 'Somalia', 'key' => '+252', 'icon' => 'https://flagcdn.com/w80/so.png'],
            ['name' => 'South Africa', 'key' => '+27', 'icon' => 'https://flagcdn.com/w80/za.png'],
            ['name' => 'South Korea', 'key' => '+82', 'icon' => 'https://flagcdn.com/w80/kr.png'],
            ['name' => 'South Sudan', 'key' => '+211', 'icon' => 'https://flagcdn.com/w80/ss.png'],
            ['name' => 'Spain', 'key' => '+34', 'icon' => 'https://flagcdn.com/w80/es.png'],
            ['name' => 'Sri Lanka', 'key' => '+94', 'icon' => 'https://flagcdn.com/w80/lk.png'],
            ['name' => 'Sudan', 'key' => '+249', 'icon' => 'https://flagcdn.com/w80/sd.png'],
            ['name' => 'Suriname', 'key' => '+597', 'icon' => 'https://flagcdn.com/w80/sr.png'],
            ['name' => 'Sweden', 'key' => '+46', 'icon' => 'https://flagcdn.com/w80/se.png'],
            ['name' => 'Switzerland', 'key' => '+41', 'icon' => 'https://flagcdn.com/w80/ch.png'],
            ['name' => 'Syria', 'key' => '+963', 'icon' => 'https://flagcdn.com/w80/sy.png'],
            ['name' => 'Taiwan', 'key' => '+886', 'icon' => 'https://flagcdn.com/w80/tw.png'],
            ['name' => 'Tajikistan', 'key' => '+992', 'icon' => 'https://flagcdn.com/w80/tj.png'],
            ['name' => 'Tanzania', 'key' => '+255', 'icon' => 'https://flagcdn.com/w80/tz.png'],
            ['name' => 'Thailand', 'key' => '+66', 'icon' => 'https://flagcdn.com/w80/th.png'],
            ['name' => 'Timor-Leste', 'key' => '+670', 'icon' => 'https://flagcdn.com/w80/tl.png'],
            ['name' => 'Togo', 'key' => '+228', 'icon' => 'https://flagcdn.com/w80/tg.png'],
            ['name' => 'Tonga', 'key' => '+676', 'icon' => 'https://flagcdn.com/w80/to.png'],
            ['name' => 'Trinidad and Tobago', 'key' => '+1-868', 'icon' => 'https://flagcdn.com/w80/tt.png'],
            ['name' => 'Tunisia', 'key' => '+216', 'icon' => 'https://flagcdn.com/w80/tn.png'],
            ['name' => 'Turkey', 'key' => '+90', 'icon' => 'https://flagcdn.com/w80/tr.png'],
            ['name' => 'Turkmenistan', 'key' => '+993', 'icon' => 'https://flagcdn.com/w80/tm.png'],
            ['name' => 'Tuvalu', 'key' => '+688', 'icon' => 'https://flagcdn.com/w80/tv.png'],
            ['name' => 'Uganda', 'key' => '+256', 'icon' => 'https://flagcdn.com/w80/ug.png'],
            ['name' => 'Ukraine', 'key' => '+380', 'icon' => 'https://flagcdn.com/w80/ua.png'],
            ['name' => 'United Arab Emirates', 'key' => '+971', 'icon' => 'https://flagcdn.com/w80/ae.png'],
            ['name' => 'United Kingdom', 'key' => '+44', 'icon' => 'https://flagcdn.com/w80/gb.png'],
            ['name' => 'United States', 'key' => '+1', 'icon' => 'https://flagcdn.com/w80/us.png'],
            ['name' => 'Uruguay', 'key' => '+598', 'icon' => 'https://flagcdn.com/w80/uy.png'],
            ['name' => 'Uzbekistan', 'key' => '+998', 'icon' => 'https://flagcdn.com/w80/uz.png'],
            ['name' => 'Vanuatu', 'key' => '+678', 'icon' => 'https://flagcdn.com/w80/vu.png'],
            ['name' => 'Vatican City', 'key' => '+39-06', 'icon' => 'https://flagcdn.com/w80/va.png'],
            ['name' => 'Venezuela', 'key' => '+58', 'icon' => 'https://flagcdn.com/w80/ve.png'],
            ['name' => 'Vietnam', 'key' => '+84', 'icon' => 'https://flagcdn.com/w80/vn.png'],
            ['name' => 'Yemen', 'key' => '+967', 'icon' => 'https://flagcdn.com/w80/ye.png'],
            ['name' => 'Zambia', 'key' => '+260', 'icon' => 'https://flagcdn.com/w80/zm.png'],
            ['name' => 'Zimbabwe', 'key' => '+263', 'icon' => 'https://flagcdn.com/w80/zw.png'],
        ];

        $now = now();

        $rows = array_map(fn ($c) => array_merge($c, [
            'is_active' => true,
            'created_at' => $now,
            'updated_at' => $now,
        ]), $countries);

        // Insert in chunks to avoid hitting query size limits
        foreach (array_chunk($rows, 50) as $chunk) {
            DB::table('keys')->insertOrIgnore($chunk);
        }
    }
}
